<?php

$uid = uniqid('wpe-slick-');
//convert _ keys to CamelCase
//WordPress shortcodes only accept attribute names with the _ separator, will not accept camel case. Slick attributes are CamelCase..
//
$slickAtts = [];
if (!isset($atts['show_thumbs'])) $atts['show_thumbs'] = 'false';

foreach ($atts as $att => $val) {
    //only atts that have been set
    //Converting Sting boolean and INT values to proper data types.
    if ($val !== "") {
        $slickAtts[\WPEasyLibrary\Helpers\Utils\StringUtils::dashToCamelCase($att)] = \WPEasyLibrary\Helpers\Utils\StringUtils::stringToDataType($val);
    }
}

if ($atts['show_thumbs'] === 'true') {
    $slickAtts['asNavFor'] = '.' . $uid . '_nav';
}

$slickJson = json_encode($slickAtts);

?>
<div class="<?= $atts['container_class'] . ' ' . $uid ?> wpe-slick-slider " data-slick='<?= $slickJson ?>'>
    <? foreach ($images as $image): ?>
        <img data-lazy="<?= $image['full'] ?>"/>
    <? endforeach; ?>
</div>

<!-- Thumbnail Nav -->
<?php if ($atts['show_thumbs'] === 'true'): ?>
    <div class="wpe-slick-thumbs <?= $uid . '_nav' ?> wpe-slick-slider"
         data-slick='{"asNavFor":".<?= $uid ?>","focusOnSelect":true,"centerMode":true,"adaptiveHeight":true,"autoplay":false,"arrows":true,"rows":1,"slidesPerRow":1,"slidesToShow":6,"slidesToScroll":1,"speed":300,"swipe":true,"swipeToSlide":true,"touchMove":true}'>
        <? foreach ($images as $image): ?>
            <img src="<?= $image['thumb'] ?>"/>
        <? endforeach; ?>
    </div>

<?php endif; ?>

<script>
    (function ($) {
        let $wpeSliders;
        let uuid = '<?= $uid ?>';
        let selector = '.' + uuid + ', .' + uuid + '_nav';

        //Need to wait for slick to be available.
        //I sin common.bundle.js loaded in the footer.
        $(document).ready(function () {
            $wpeSliders = $(selector).not('.slick-initialized');
            $wpeSliders.slick();
        });
    })(jQuery)
</script>
